name: Integrated Swag Labs Web UI and Gorest API Testing Framework

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
 run-api-automation-test:
   runs-on: ubuntu-latest

   permissions:
     contents: write
   
   steps:
   - name: Checkout code
     uses: actions/checkout@v4
  
   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
       java-version: '17'
       distribution: 'temurin'    

   - name: Setup Gradlew
     run: chmod +x gradlew

   - name: Run API Automation Test
     run: ./gradlew apiTest

   - name: Archive Test Result
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: API Test Report
       path: reports/cucumber-api.html
    
   - name: Deploy report to Github Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
       PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
       PUBLISH_DIR: ./public
   
 run-web-automation-test:
   runs-on: ubuntu-latest

   permissions:
     contents: write

   steps:
   - name: Checkout code
     uses: actions/checkout@v4
  
   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
       java-version: '17'
       distribution: 'temurin'

   - name: Setup Chrome
     uses: browser-actions/setup-chrome@v1.7.2       

   - name: Setup Gradlew
     run: chmod +x gradlew

   - name: Run Web Automation Test
     run: ./gradlew webTest

   - name: Archive Test Result
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: Web Test Report
       path: reports/cucumber-web.html
    
   - name: Deploy report to Github Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
       PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
       PUBLISH_DIR: ./public
